// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function CreateProject(arg1:string,arg2:string):Promise<main.WailsProject>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<main.WailsProject>;

export function Handler():Promise<http.Handler>;

export function ListProjects():Promise<Array<main.WailsProject>>;
