// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateWorkspace(arg1:string,arg2:string):Promise<main.WailsWorkspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetWorkspace(arg1:string):Promise<main.WailsWorkspace>;

export function ListWorkspaces():Promise<Array<main.WailsWorkspace>>;
