// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}
