# GoReleaser configuration for nebi
version: 2

before:
  hooks:
    # Build frontend before creating release
    - sh -c "cd frontend && npm install && npm run build"
    # Copy frontend dist to internal/web/dist for embedding
    - sh -c "rm -rf internal/web/dist && cp -r frontend/dist internal/web/dist"

builds:
  - id: nebi
    main: ./cmd/nebi
    binary: nebi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: nebi
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Enhancements'
      regexp: "^.*enhancement[(\\w)]*:+.*$"
      order: 2
    - title: 'Others'
      order: 999

release:
  github:
    owner: nebari-dev
    name: nebi
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## nebi {{ .Tag }} ({{ .Date }})

    Welcome to this new release of nebi!
  footer: |
    ## Installation

    ### Binary Installation

    Download the appropriate binary for your platform from the assets below.

    ---

    **Full Changelog**: https://github.com/nebari-dev/nebi/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
