name: Feature request
description: Suggest a new feature or improvement
title: "[FEAT] -  "
labels: ["type: enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature or improvement you'd like.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other solutions?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other details or screenshots.