package auth

import (
	"crypto/rand"
	"encoding/hex"
	"sync"
	"time"
)

const authCodeTTL = 30 * time.Second // Short-lived: only needs to survive the redirect

// AuthCodeEntry holds a single-use authorization code and the session it grants.
type AuthCodeEntry struct {
	Token     string // Nebi JWT
	UserJSON  []byte // Serialized user object
	expiresAt time.Time
}

// AuthCodeStore is a thread-safe in-memory store for single-use authorization codes.
// Codes are generated by the gateway session redirect and exchanged by the frontend.
type AuthCodeStore struct {
	mu      sync.Mutex
	entries map[string]*AuthCodeEntry
}

// NewAuthCodeStore creates a new authorization code store.
func NewAuthCodeStore() *AuthCodeStore {
	return &AuthCodeStore{
		entries: make(map[string]*AuthCodeEntry),
	}
}

// Generate creates a cryptographically random authorization code, stores it
// with the associated session data, and returns the code.
func (s *AuthCodeStore) Generate(token string, userJSON []byte) (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	code := hex.EncodeToString(b)

	s.mu.Lock()
	defer s.mu.Unlock()

	// Clean up expired entries
	now := time.Now()
	for k, entry := range s.entries {
		if now.After(entry.expiresAt) {
			delete(s.entries, k)
		}
	}

	s.entries[code] = &AuthCodeEntry{
		Token:     token,
		UserJSON:  userJSON,
		expiresAt: now.Add(authCodeTTL),
	}
	return code, nil
}

// Exchange consumes a code and returns the associated session data.
// The code is deleted after use (single-use). Returns false if the code
// is invalid, expired, or already consumed.
func (s *AuthCodeStore) Exchange(code string) (token string, userJSON []byte, ok bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	entry, exists := s.entries[code]
	if !exists || time.Now().After(entry.expiresAt) {
		delete(s.entries, code) // clean up if expired
		return "", nil, false
	}

	// Single-use: delete immediately
	delete(s.entries, code)
	return entry.Token, entry.UserJSON, true
}
